name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.89.0
        with:
          ruby-version: 3.0
          bundler-cache: true
      - run: bundle install
      - name: build
        run: |
          bundle exec jekyll build
      - name: nojekyll
        run: touch .nojekyll
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
